# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Analyser.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_AnalyserWidget(object):
    def setupUi(self, AnalyserWidget):
        AnalyserWidget.setObjectName("AnalyserWidget")
        AnalyserWidget.resize(750, 350)
        self.gridLayout = QtWidgets.QGridLayout(AnalyserWidget)
        self.gridLayout.setSpacing(10)
        self.gridLayout.setObjectName("gridLayout")
        self.btnRefresh = QtWidgets.QPushButton(AnalyserWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btnRefresh.sizePolicy().hasHeightForWidth())
        self.btnRefresh.setSizePolicy(sizePolicy)
        self.btnRefresh.setObjectName("btnRefresh")
        self.gridLayout.addWidget(self.btnRefresh, 0, 1, 1, 1)

        self.retranslateUi(AnalyserWidget)
        QtCore.QMetaObject.connectSlotsByName(AnalyserWidget)

    def retranslateUi(self, AnalyserWidget):
        _translate = QtCore.QCoreApplication.translate
        self.btnRefresh.setText(_translate("AnalyserWidget", "Show Matrix"))
