# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui/page/Converter.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_ConverterWidget(object):
    def setupUi(self, ConverterWidget):
        ConverterWidget.setObjectName("ConverterWidget")
        self.gridLayout = QtWidgets.QGridLayout(ConverterWidget)
        self.gridLayout.setSpacing(8)
        self.gridLayout.setObjectName("gridLayout")
        self.labelHint = QtWidgets.QLabel(ConverterWidget)
        self.labelHint.setWordWrap(True)
        self.labelHint.setStyleSheet("color: gray; font-size: 9pt; padding-left: 16px; text-align: left")
        self.labelHint.setObjectName("labelHint")
        self.gridLayout.addWidget(self.labelHint, 0, 0, 1, 8)
        self.layoutFile = QtWidgets.QHBoxLayout()
        self.layoutFile.setObjectName("layoutFile")
        self.editFilePath = QtWidgets.QLineEdit(ConverterWidget)
        self.editFilePath.setReadOnly(True)
        self.editFilePath.setObjectName("editFilePath")
        self.layoutFile.addWidget(self.editFilePath)
        self.buttonBrowse = QtWidgets.QPushButton(ConverterWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.buttonBrowse.sizePolicy().hasHeightForWidth())
        self.buttonBrowse.setSizePolicy(sizePolicy)
        self.buttonBrowse.setObjectName("buttonBrowse")
        self.layoutFile.addWidget(self.buttonBrowse)
        self.gridLayout.addLayout(self.layoutFile, 1, 0, 1, 8)
        self.buttonConvert = QtWidgets.QPushButton(ConverterWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.buttonConvert.sizePolicy().hasHeightForWidth())
        self.buttonConvert.setSizePolicy(sizePolicy)
        self.buttonConvert.setObjectName("buttonConvert")
        self.gridLayout.addWidget(self.buttonConvert, 2, 0, 1, 8, QtCore.Qt.AlignHCenter)
        spacerItem = QtWidgets.QSpacerItem(20, 0, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem)

        self.retranslateUi(ConverterWidget)
        QtCore.QMetaObject.connectSlotsByName(ConverterWidget)

    def retranslateUi(self, ConverterWidget):
        _translate = QtCore.QCoreApplication.translate
        self.labelHint.setText(_translate("ConverterWidget", "\n"
"                            Select a BLF file below, and the convert button will convert the BLF to ASC.<br/>\n"
"                            The ASC file will be placed into the same directory of BLF file.\n"
"                        "))
        self.editFilePath.setPlaceholderText(_translate("ConverterWidget", "Select a BLF file..."))
        self.buttonBrowse.setText(_translate("ConverterWidget", "Browse"))
        self.buttonConvert.setText(_translate("ConverterWidget", "Convert"))
