# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Converter.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_ConverterWidget(object):
    def setupUi(self, ConverterWidget):
        ConverterWidget.setObjectName("ConverterWidget")
        ConverterWidget.resize(750, 350)
        self.gridLayout = QtWidgets.QGridLayout(ConverterWidget)
        self.gridLayout.setSpacing(10)
        self.gridLayout.setObjectName("gridLayout")
        self.labelHint = QtWidgets.QLabel(ConverterWidget)
        self.labelHint.setWordWrap(True)
        self.labelHint.setStyleSheet("color: gray; font-size: 9pt;")
        self.labelHint.setObjectName("labelHint")
        self.gridLayout.addWidget(self.labelHint, 0, 0, 1, 8)
        self.fileLayout = QtWidgets.QHBoxLayout()
        self.fileLayout.setObjectName("fileLayout")
        self.filePathEdit = QtWidgets.QLineEdit(ConverterWidget)
        self.filePathEdit.setObjectName("filePathEdit")
        self.fileLayout.addWidget(self.filePathEdit)
        self.browseButton = QtWidgets.QPushButton(ConverterWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.browseButton.sizePolicy().hasHeightForWidth())
        self.browseButton.setSizePolicy(sizePolicy)
        self.browseButton.setObjectName("browseButton")
        self.fileLayout.addWidget(self.browseButton)
        self.gridLayout.addLayout(self.fileLayout, 1, 0, 1, 10)
        self.convertButton = QtWidgets.QPushButton(ConverterWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.convertButton.sizePolicy().hasHeightForWidth())
        self.convertButton.setSizePolicy(sizePolicy)
        self.convertButton.setObjectName("convertButton")
        self.gridLayout.addWidget(self.convertButton, 2, 0, 1, 10, QtCore.Qt.AlignHCenter)
        spacerItem = QtWidgets.QSpacerItem(20, 0, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem)

        self.retranslateUi(ConverterWidget)
        QtCore.QMetaObject.connectSlotsByName(ConverterWidget)

    def retranslateUi(self, ConverterWidget):
        _translate = QtCore.QCoreApplication.translate
        self.labelHint.setText(_translate("ConverterWidget", "\n"
"                            Select a BLF file below, and the convert button will convert the BLF to ASC.<br/>\n"
"                            The ASC file will be placed into the same directory of BLF file.\n"
"                        "))
        self.filePathEdit.setPlaceholderText(_translate("ConverterWidget", "Select a BLF file..."))
        self.browseButton.setText(_translate("ConverterWidget", "Browse"))
        self.convertButton.setText(_translate("ConverterWidget", "Convert"))
