# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui/page/Generator.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_GeneratorWidget(object):
    def setupUi(self, GeneratorWidget):
        GeneratorWidget.setObjectName("GeneratorWidget")
        GeneratorWidget.resize(750, 350)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(GeneratorWidget.sizePolicy().hasHeightForWidth())
        GeneratorWidget.setSizePolicy(sizePolicy)
        self.verticalLayout = QtWidgets.QVBoxLayout(GeneratorWidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.contentWidget = QtWidgets.QWidget(GeneratorWidget)
        self.contentWidget.setObjectName("contentWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.contentWidget)
        self.gridLayout.setObjectName("gridLayout")
        self.labelResult = QtWidgets.QLabel(self.contentWidget)
        self.labelResult.setObjectName("labelResult")
        self.gridLayout.addWidget(self.labelResult, 0, 0, 1, 8)
        self.radioRaw = QtWidgets.QRadioButton(self.contentWidget)
        self.radioRaw.setChecked(True)
        self.radioRaw.setObjectName("radioRaw")
        self.gridLayout.addWidget(self.radioRaw, 1, 2, 1, 1)
        self.spinRaw = QtWidgets.QSpinBox(self.contentWidget)
        self.spinRaw.setMinimum(0)
        self.spinRaw.setProperty("value", 0)
        self.spinRaw.setMaximum(999999)
        self.spinRaw.setObjectName("spinRaw")
        self.gridLayout.addWidget(self.spinRaw, 1, 3, 1, 1)
        self.radioPhysical = QtWidgets.QRadioButton(self.contentWidget)
        self.radioPhysical.setObjectName("radioPhysical")
        self.gridLayout.addWidget(self.radioPhysical, 1, 4, 1, 1)
        self.spinPhysical = QtWidgets.QDoubleSpinBox(self.contentWidget)
        self.spinPhysical.setDecimals(6)
        self.spinPhysical.setMinimum(-1000000.0)
        self.spinPhysical.setMaximum(1000000.0)
        self.spinPhysical.setProperty("value", 0.0)
        self.spinPhysical.setObjectName("spinPhysical")
        self.gridLayout.addWidget(self.spinPhysical, 1, 5, 1, 1)
        self.btnGenerate = QtWidgets.QPushButton(self.contentWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btnGenerate.sizePolicy().hasHeightForWidth())
        self.btnGenerate.setSizePolicy(sizePolicy)
        self.btnGenerate.setObjectName("btnGenerate")
        self.gridLayout.addWidget(self.btnGenerate, 2, 0, 1, 8, QtCore.Qt.AlignHCenter)
        self.labelResult1 = QtWidgets.QLabel(self.contentWidget)
        self.labelResult1.setObjectName("labelResult1")
        self.gridLayout.addWidget(self.labelResult1, 3, 0, 1, 8)
        self.editResult = QtWidgets.QLineEdit(self.contentWidget)
        self.editResult.setReadOnly(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.editResult.sizePolicy().hasHeightForWidth())
        self.editResult.setSizePolicy(sizePolicy)
        self.editResult.setMinimumSize(QtCore.QSize(0, 30))
        self.editResult.setMaximumSize(QtCore.QSize(16777215, 30))
        self.editResult.setObjectName("editResult")
        self.gridLayout.addWidget(self.editResult, 4, 0, 1, 8)
        self.verticalLayout.addWidget(self.contentWidget)
        spacerItem = QtWidgets.QSpacerItem(20, 0, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem)

        self.retranslateUi(GeneratorWidget)
        QtCore.QMetaObject.connectSlotsByName(GeneratorWidget)

    def retranslateUi(self, GeneratorWidget):
        _translate = QtCore.QCoreApplication.translate
        self.labelResult.setText(_translate("GeneratorWidget", "【Value】"))
        self.radioRaw.setText(_translate("GeneratorWidget", "Raw Value"))
        self.radioPhysical.setText(_translate("GeneratorWidget", "Physical Value"))
        self.btnGenerate.setText(_translate("GeneratorWidget", "Generate"))
        self.labelResult1.setText(_translate("GeneratorWidget", "【Generated CAN Message】"))
        self.editResult.setPlaceholderText(_translate("GeneratorWidget", "Generated CAN message will appear here..."))
