# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Home.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(750, 600)
        self.centralWidget = QtWidgets.QWidget(MainWindow)
        self.centralWidget.setObjectName("centralWidget")
        self.mainLayout = QtWidgets.QVBoxLayout(self.centralWidget)
        self.mainLayout.setObjectName("mainLayout")
        self.groupBoxParams = QtWidgets.QGroupBox(self.centralWidget)
        self.groupBoxParams.setObjectName("groupBoxParams")
        self.paramsLayout = QtWidgets.QGridLayout(self.groupBoxParams)
        self.paramsLayout.setSpacing(10)
        self.paramsLayout.setObjectName("paramsLayout")
        self.labelFormat = QtWidgets.QLabel(self.groupBoxParams)
        self.labelFormat.setObjectName("labelFormat")
        self.paramsLayout.addWidget(self.labelFormat, 0, 0, 1, 2)
        self.comboFormat = QtWidgets.QComboBox(self.groupBoxParams)
        self.comboFormat.setObjectName("comboFormat")
        self.paramsLayout.addWidget(self.comboFormat, 0, 2, 1, 2)
        self.labelBytes = QtWidgets.QLabel(self.groupBoxParams)
        self.labelBytes.setObjectName("labelBytes")
        self.paramsLayout.addWidget(self.labelBytes, 0, 6, 1, 1)
        self.spinBytesLength = QtWidgets.QSpinBox(self.groupBoxParams)
        self.spinBytesLength.setMinimum(1)
        self.spinBytesLength.setProperty("value", 8)
        self.spinBytesLength.setObjectName("spinBytesLength")
        self.paramsLayout.addWidget(self.spinBytesLength, 0, 7, 1, 1)
        self.labelStartBit = QtWidgets.QLabel(self.groupBoxParams)
        self.labelStartBit.setObjectName("labelStartBit")
        self.paramsLayout.addWidget(self.labelStartBit, 1, 0, 1, 1)
        self.spinStartBit = QtWidgets.QSpinBox(self.groupBoxParams)
        self.spinStartBit.setMinimum(0)
        self.spinStartBit.setMaximum(511)
        self.spinStartBit.setProperty("value", 0)
        self.spinStartBit.setObjectName("spinStartBit")
        self.paramsLayout.addWidget(self.spinStartBit, 1, 1, 1, 1)
        self.labelBitLength = QtWidgets.QLabel(self.groupBoxParams)
        self.labelBitLength.setObjectName("labelBitLength")
        self.paramsLayout.addWidget(self.labelBitLength, 1, 2, 1, 1)
        self.spinBitLength = QtWidgets.QSpinBox(self.groupBoxParams)
        self.spinBitLength.setMinimum(1)
        self.spinBitLength.setMaximum(64)
        self.spinBitLength.setProperty("value", 8)
        self.spinBitLength.setObjectName("spinBitLength")
        self.paramsLayout.addWidget(self.spinBitLength, 1, 3, 1, 1)
        self.labelFactor = QtWidgets.QLabel(self.groupBoxParams)
        self.labelFactor.setObjectName("labelFactor")
        self.paramsLayout.addWidget(self.labelFactor, 1, 4, 1, 1)
        self.spinFactor = QtWidgets.QDoubleSpinBox(self.groupBoxParams)
        self.spinFactor.setDecimals(6)
        self.spinFactor.setMinimum(1e-06)
        self.spinFactor.setMaximum(1000000.0)
        self.spinFactor.setProperty("value", 1.0)
        self.spinFactor.setObjectName("spinFactor")
        self.paramsLayout.addWidget(self.spinFactor, 1, 5, 1, 1)
        self.labelOffset = QtWidgets.QLabel(self.groupBoxParams)
        self.labelOffset.setObjectName("labelOffset")
        self.paramsLayout.addWidget(self.labelOffset, 1, 6, 1, 1)
        self.spinOffset = QtWidgets.QDoubleSpinBox(self.groupBoxParams)
        self.spinOffset.setDecimals(6)
        self.spinOffset.setMinimum(-1000000.0)
        self.spinOffset.setMaximum(1000000.0)
        self.spinOffset.setProperty("value", 0.0)
        self.spinOffset.setObjectName("spinOffset")
        self.paramsLayout.addWidget(self.spinOffset, 1, 7, 1, 1)
        self.mainLayout.addWidget(self.groupBoxParams)
        self.tabWidget = QtWidgets.QTabWidget(self.centralWidget)
        self.tabWidget.setObjectName("tabWidget")
        self.mainLayout.addWidget(self.tabWidget)
        MainWindow.setCentralWidget(self.centralWidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "CAN Tool"))
        self.groupBoxParams.setTitle(_translate("MainWindow", "Matrix Information"))
        self.labelFormat.setText(_translate("MainWindow", "Format"))
        self.labelBytes.setText(_translate("MainWindow", "Bytes Length"))
        self.labelStartBit.setText(_translate("MainWindow", "Start Bit"))
        self.labelBitLength.setText(_translate("MainWindow", "Bit length"))
        self.labelFactor.setText(_translate("MainWindow", "Factor"))
        self.labelOffset.setText(_translate("MainWindow", "Offset"))
