# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui/page/Matrix.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MatrixWidget(object):
    def setupUi(self, MatrixWidget):
        MatrixWidget.setObjectName("MatrixWidget")
        MatrixWidget.resize(750, 350)
        self.gridLayout = QtWidgets.QGridLayout(MatrixWidget)
        self.gridLayout.setSpacing(10)
        self.gridLayout.setObjectName("gridLayout")
        self.btnRefresh = QtWidgets.QPushButton(MatrixWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btnRefresh.sizePolicy().hasHeightForWidth())
        self.btnRefresh.setSizePolicy(sizePolicy)
        self.btnRefresh.setObjectName("btnRefresh")
        self.gridLayout.addWidget(self.btnRefresh, 0, 0, 1, 8, QtCore.Qt.AlignHCenter)
        self.tableMatrix = QtWidgets.QTableWidget(MatrixWidget)
        self.tableMatrix.setRowCount(0)
        self.tableMatrix.setColumnCount(8)
        self.tableMatrix.setObjectName("tableMatrix")
        self.tableMatrix.horizontalHeader().setVisible(True)
        self.tableMatrix.verticalHeader().setVisible(True)
        self.gridLayout.addWidget(self.tableMatrix, 1, 0, 1, 8)

        self.retranslateUi(MatrixWidget)
        QtCore.QMetaObject.connectSlotsByName(MatrixWidget)

    def retranslateUi(self, MatrixWidget):
        _translate = QtCore.QCoreApplication.translate
        self.btnRefresh.setText(_translate("MatrixWidget", "Refresh"))
