# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Parser.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_ParserWidget(object):
    def setupUi(self, ParserWidget):
        ParserWidget.setObjectName("ParserWidget")
        ParserWidget.resize(750, 350)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(ParserWidget.sizePolicy().hasHeightForWidth())
        ParserWidget.setSizePolicy(sizePolicy)
        self.verticalLayout = QtWidgets.QVBoxLayout(ParserWidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.contentWidget = QtWidgets.QWidget(ParserWidget)
        self.contentWidget.setObjectName("contentWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.contentWidget)
        self.gridLayout.setSpacing(10)
        self.gridLayout.setObjectName("gridLayout")
        self.labelData = QtWidgets.QLabel(self.contentWidget)
        self.labelData.setObjectName("labelData")
        self.gridLayout.addWidget(self.labelData, 0, 0, 1, 8)
        self.labelHint = QtWidgets.QLabel(self.contentWidget)
        self.labelHint.setWordWrap(True)
        self.labelHint.setStyleSheet("color: gray; font-size: 9pt;")
        self.labelHint.setObjectName("labelHint")
        self.gridLayout.addWidget(self.labelHint, 1, 0, 1, 8)
        self.editData = QtWidgets.QLineEdit(self.contentWidget)
        self.editData.setObjectName("editData")
        self.gridLayout.addWidget(self.editData, 2, 0, 1, 8)
        self.btnParse = QtWidgets.QPushButton(self.contentWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btnParse.sizePolicy().hasHeightForWidth())
        self.btnParse.setSizePolicy(sizePolicy)
        self.btnParse.setObjectName("btnParse")
        self.gridLayout.addWidget(self.btnParse, 3, 0, 1, 8, QtCore.Qt.AlignHCenter)
        self.labelRaw = QtWidgets.QLabel(self.contentWidget)
        self.labelRaw.setObjectName("labelRaw")
        self.gridLayout.addWidget(self.labelRaw, 4, 2, 1, 1)
        self.editRaw = QtWidgets.QLineEdit(self.contentWidget)
        self.editRaw.setReadOnly(True)
        self.editRaw.setObjectName("editRaw")
        self.gridLayout.addWidget(self.editRaw, 4, 3, 1, 1)
        self.labelPhysical = QtWidgets.QLabel(self.contentWidget)
        self.labelPhysical.setObjectName("labelPhysical")
        self.gridLayout.addWidget(self.labelPhysical, 4, 4, 1, 1)
        self.editPhysical = QtWidgets.QLineEdit(self.contentWidget)
        self.editPhysical.setReadOnly(True)
        self.editPhysical.setObjectName("editPhysical")
        self.gridLayout.addWidget(self.editPhysical, 4, 5, 1, 1)
        self.verticalLayout.addWidget(self.contentWidget)
        spacerItem = QtWidgets.QSpacerItem(20, 0, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem)

        self.retranslateUi(ParserWidget)
        QtCore.QMetaObject.connectSlotsByName(ParserWidget)

    def retranslateUi(self, ParserWidget):
        _translate = QtCore.QCoreApplication.translate
        self.labelData.setText(_translate("ParserWidget", "CAN Message"))
        self.labelHint.setText(_translate("ParserWidget", "\n"
"                                        Format in hex, each byte separated by space or comma.<br/>\n"
"                                        Bytes order like: Byte0 Byte1 ...<br/>\n"
"                                        For example: 00 01 98 00 or 00,01,98,00\n"
"                                    "))
        self.editData.setPlaceholderText(_translate("ParserWidget", "Enter hex bytes..."))
        self.btnParse.setText(_translate("ParserWidget", "Parse"))
        self.labelRaw.setText(_translate("ParserWidget", "Raw Value"))
        self.labelPhysical.setText(_translate("ParserWidget", "Physical Value"))
