# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui/page/Settings.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_SettingsWidget(object):
    def setupUi(self, SettingsWidget):
        SettingsWidget.setObjectName("SettingsWidget")
        self.mainLayout = QtWidgets.QVBoxLayout(SettingsWidget)
        self.mainLayout.setContentsMargins(20, 20, 20, 10)
        self.mainLayout.setSpacing(10)
        self.mainLayout.setObjectName("mainLayout")
        self.categoryGeneral = QtWidgets.QLabel(SettingsWidget)
        self.categoryGeneral.setObjectName("categoryGeneral")
        self.mainLayout.addWidget(self.categoryGeneral)
        self.layoutGeneral1 = QtWidgets.QHBoxLayout()
        self.layoutGeneral1.setSpacing(20)
        self.layoutGeneral1.setObjectName("layoutGeneral1")
        self.settingsTheme = QtWidgets.QWidget(SettingsWidget)
        self.settingsTheme.setObjectName("settingsTheme")
        self.layoutTheme = QtWidgets.QHBoxLayout(self.settingsTheme)
        self.layoutTheme.setObjectName("layoutTheme")
        self.labelTheme = QtWidgets.QLabel(self.settingsTheme)
        self.labelTheme.setObjectName("labelTheme")
        self.layoutTheme.addWidget(self.labelTheme)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.layoutTheme.addItem(spacerItem)
        self.toggleTheme = ToggleSwitch(self.settingsTheme)
        self.toggleTheme.setText("")
        self.toggleTheme.setObjectName("toggleTheme")
        self.layoutTheme.addWidget(self.toggleTheme)
        self.layoutGeneral1.addWidget(self.settingsTheme)
        self.settingsPlaceholder = QtWidgets.QWidget(SettingsWidget)
        self.settingsPlaceholder.setObjectName("settingsPlaceholder")
        self.layoutGeneral1.addWidget(self.settingsPlaceholder)
        self.layoutGeneral1.setStretch(0, 1)
        self.layoutGeneral1.setStretch(1, 1)
        self.mainLayout.addLayout(self.layoutGeneral1)
        self.rowFullWidthLayout = QtWidgets.QHBoxLayout()
        self.rowFullWidthLayout.setContentsMargins(9, -1, -1, -1)
        self.rowFullWidthLayout.setObjectName("rowFullWidthLayout")
        self.labelFullWidthOption = QtWidgets.QLabel(SettingsWidget)
        self.labelFullWidthOption.setObjectName("labelFullWidthOption")
        self.rowFullWidthLayout.addWidget(self.labelFullWidthOption)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.rowFullWidthLayout.addItem(spacerItem1)
        self.checkFullWidthOption = QtWidgets.QCheckBox(SettingsWidget)
        self.checkFullWidthOption.setText("")
        self.checkFullWidthOption.setObjectName("checkFullWidthOption")
        self.rowFullWidthLayout.addWidget(self.checkFullWidthOption)
        self.mainLayout.addLayout(self.rowFullWidthLayout)
        spacerItem2 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.mainLayout.addItem(spacerItem2)
        self.copyrightLabel = QtWidgets.QLabel(SettingsWidget)
        self.copyrightLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.copyrightLabel.setStyleSheet("color: #888; font-size: 10pt;")
        self.copyrightLabel.setObjectName("copyrightLabel")
        self.mainLayout.addWidget(self.copyrightLabel)

        self.retranslateUi(SettingsWidget)
        QtCore.QMetaObject.connectSlotsByName(SettingsWidget)

    def retranslateUi(self, SettingsWidget):
        _translate = QtCore.QCoreApplication.translate
        self.categoryGeneral.setText(_translate("SettingsWidget", "General"))
        self.categoryGeneral.setProperty("class", _translate("SettingsWidget", "settings-title"))
        self.labelTheme.setText(_translate("SettingsWidget", "DarkTheme"))
        self.labelFullWidthOption.setText(_translate("SettingsWidget", "TODO Option"))
        self.copyrightLabel.setText(_translate("SettingsWidget", "Copyright © 2026 Joel"))
from ui.widget.ToggleSwitch import ToggleSwitch
