# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Generator.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_GeneratorWidget(object):
    def setupUi(self, GeneratorWidget):
        GeneratorWidget.setObjectName("GeneratorWidget")
        GeneratorWidget.resize(500, 300)
        self.verticalLayout = QtWidgets.QVBoxLayout(GeneratorWidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label = QtWidgets.QLabel(GeneratorWidget)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)

        self.retranslateUi(GeneratorWidget)
        QtCore.QMetaObject.connectSlotsByName(GeneratorWidget)

    def retranslateUi(self, GeneratorWidget):
        _translate = QtCore.QCoreApplication.translate
        self.label.setText(_translate("GeneratorWidget", "Generator (to be implemented)"))
