# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Generator.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_GeneratorWidget(object):
    def setupUi(self, GeneratorWidget):
        GeneratorWidget.setObjectName("GeneratorWidget")
        GeneratorWidget.resize(500, 350)
        self.gridLayout = QtWidgets.QGridLayout(GeneratorWidget)
        self.gridLayout.setHorizontalSpacing(10)
        self.gridLayout.setVerticalSpacing(6)
        self.gridLayout.setObjectName("gridLayout")
        self.labelRaw = QtWidgets.QLabel(GeneratorWidget)
        self.labelRaw.setObjectName("labelRaw")
        self.gridLayout.addWidget(self.labelRaw, 0, 0, 1, 1)
        self.spinRaw = QtWidgets.QSpinBox(GeneratorWidget)
        self.spinRaw.setMinimum(0)
        self.spinRaw.setProperty("value", 0)
        self.spinRaw.setObjectName("spinRaw")
        self.gridLayout.addWidget(self.spinRaw, 0, 1, 1, 1)
        self.labelBytes = QtWidgets.QLabel(GeneratorWidget)
        self.labelBytes.setObjectName("labelBytes")
        self.gridLayout.addWidget(self.labelBytes, 0, 2, 1, 1)
        self.spinBytesLength = QtWidgets.QSpinBox(GeneratorWidget)
        self.spinBytesLength.setMinimum(1)
        self.spinBytesLength.setProperty("value", 8)
        self.spinBytesLength.setObjectName("spinBytesLength")
        self.gridLayout.addWidget(self.spinBytesLength, 0, 3, 1, 1)
        self.btnGenerate = QtWidgets.QPushButton(GeneratorWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btnGenerate.sizePolicy().hasHeightForWidth())
        self.btnGenerate.setSizePolicy(sizePolicy)
        self.btnGenerate.setObjectName("btnGenerate")
        self.gridLayout.addWidget(self.btnGenerate, 1, 0, 1, 4, QtCore.Qt.AlignHCenter)
        spacerItem = QtWidgets.QSpacerItem(20, 10, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem, 2, 0, 1, 4)
        self.labelResult = QtWidgets.QLabel(GeneratorWidget)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.labelResult.setFont(font)
        self.labelResult.setObjectName("labelResult")
        self.gridLayout.addWidget(self.labelResult, 3, 0, 1, 4)
        self.editResult = QtWidgets.QPlainTextEdit(GeneratorWidget)
        self.editResult.setReadOnly(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.editResult.sizePolicy().hasHeightForWidth())
        self.editResult.setSizePolicy(sizePolicy)
        self.editResult.setObjectName("editResult")
        self.gridLayout.addWidget(self.editResult, 4, 0, 1, 4)

        self.retranslateUi(GeneratorWidget)
        QtCore.QMetaObject.connectSlotsByName(GeneratorWidget)

    def retranslateUi(self, GeneratorWidget):
        _translate = QtCore.QCoreApplication.translate
        self.labelRaw.setText(_translate("GeneratorWidget", "Raw Value"))
        self.labelBytes.setText(_translate("GeneratorWidget", "Bytes Length"))
        self.btnGenerate.setText(_translate("GeneratorWidget", "Generate"))
        self.labelResult.setText(_translate("GeneratorWidget", "Generated CAN Message"))
        self.editResult.setPlaceholderText(_translate("GeneratorWidget", "Generated CAN message will appear here..."))
