# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Parser.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_ParserWidget(object):
    def setupUi(self, ParserWidget):
        ParserWidget.setObjectName("ParserWidget")
        ParserWidget.resize(500, 350)
        self.gridLayout = QtWidgets.QGridLayout(ParserWidget)
        self.gridLayout.setHorizontalSpacing(10)
        self.gridLayout.setVerticalSpacing(6)
        self.gridLayout.setObjectName("gridLayout")
        self.labelFactor = QtWidgets.QLabel(ParserWidget)
        self.labelFactor.setObjectName("labelFactor")
        self.gridLayout.addWidget(self.labelFactor, 0, 0, 1, 1)
        self.spinFactor = QtWidgets.QDoubleSpinBox(ParserWidget)
        self.spinFactor.setDecimals(6)
        self.spinFactor.setMinimum(-1000000.0)
        self.spinFactor.setMaximum(1000000.0)
        self.spinFactor.setProperty("value", 1.0)
        self.spinFactor.setObjectName("spinFactor")
        self.gridLayout.addWidget(self.spinFactor, 0, 1, 1, 1)
        self.labelOffset = QtWidgets.QLabel(ParserWidget)
        self.labelOffset.setObjectName("labelOffset")
        self.gridLayout.addWidget(self.labelOffset, 0, 2, 1, 1)
        self.spinOffset = QtWidgets.QDoubleSpinBox(ParserWidget)
        self.spinOffset.setDecimals(6)
        self.spinOffset.setMinimum(-1000000.0)
        self.spinOffset.setMaximum(1000000.0)
        self.spinOffset.setProperty("value", 0.0)
        self.spinOffset.setObjectName("spinOffset")
        self.gridLayout.addWidget(self.spinOffset, 0, 3, 1, 1)
        self.labelData = QtWidgets.QLabel(ParserWidget)
        self.labelData.setObjectName("labelData")
        self.gridLayout.addWidget(self.labelData, 1, 0, 1, 4)
        self.editData = QtWidgets.QPlainTextEdit(ParserWidget)
        self.editData.setObjectName("editData")
        self.gridLayout.addWidget(self.editData, 2, 0, 1, 4)
        self.btnParse = QtWidgets.QPushButton(ParserWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btnParse.sizePolicy().hasHeightForWidth())
        self.btnParse.setSizePolicy(sizePolicy)
        self.btnParse.setObjectName("btnParse")
        self.gridLayout.addWidget(self.btnParse, 3, 0, 1, 4, QtCore.Qt.AlignHCenter)
        spacerItem = QtWidgets.QSpacerItem(20, 0, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem, 4, 0, 1, 4)
        self.labelRaw = QtWidgets.QLabel(ParserWidget)
        self.labelRaw.setObjectName("labelRaw")
        self.gridLayout.addWidget(self.labelRaw, 5, 0, 1, 1)
        self.editRaw = QtWidgets.QLineEdit(ParserWidget)
        self.editRaw.setReadOnly(True)
        self.editRaw.setObjectName("editRaw")
        self.gridLayout.addWidget(self.editRaw, 5, 1, 1, 1)
        self.labelPhysical = QtWidgets.QLabel(ParserWidget)
        self.labelPhysical.setObjectName("labelPhysical")
        self.gridLayout.addWidget(self.labelPhysical, 5, 2, 1, 1)
        self.editPhysical = QtWidgets.QLineEdit(ParserWidget)
        self.editPhysical.setReadOnly(True)
        self.editPhysical.setObjectName("editPhysical")
        self.gridLayout.addWidget(self.editPhysical, 5, 3, 1, 1)

        self.retranslateUi(ParserWidget)
        QtCore.QMetaObject.connectSlotsByName(ParserWidget)

    def retranslateUi(self, ParserWidget):
        _translate = QtCore.QCoreApplication.translate
        self.labelFactor.setText(_translate("ParserWidget", "Factor"))
        self.labelOffset.setText(_translate("ParserWidget", "Offset"))
        self.labelData.setText(_translate("ParserWidget", "CAN Message"))
        self.editData.setPlaceholderText(_translate("ParserWidget", "Format in hex, each byte separated by space or comma. Bytes order like: Byte0 Byte1 ... For example: 00 01 98 00 or 00,01,98,00"))
        self.btnParse.setText(_translate("ParserWidget", "Parse"))
        self.labelRaw.setText(_translate("ParserWidget", "Raw Value"))
        self.labelPhysical.setText(_translate("ParserWidget", "Physical Value"))
